#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Authors:    Admin9705, Deiteq, and many PGBlitz Contributors
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: include PGClone aliases
      include_tasks: '/opt/pgclone/bin/bin.yml'

    - name: include PGClone cron jobs
      include_tasks: '/opt/pgclone/ymls/cron.yml'

    - name: Register hdpath
      shell: 'cat /var/plexguide/server.hd.path'
      register: hdpath

    - debug: msg="Combined Path - {{multihds}}"

    - name: Install Union Script
      template:
        src: /opt/pgclone/mounts/local.sh
        dest: /opt/appdata/plexguide/pgunion.sh
        force: yes

    - name: Install PGUnion Service
      template:
        src: /opt/pgclone/mounts/pgunion.service
        dest: /etc/systemd/system/pgunion.service
        force: yes

    - name: Reload PGUnion Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: pgunion

    - name: Sleep 2 Seconds
      wait_for: timeout=2
